<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />


<script src="javascript/cufon-yui.js" type="text/javascript"></script>
<script src="javascript/Neuropol_400.font.js" type="text/javascript"></script>
<script type="text/javascript">
			Cufon.replace('h1');
		</script>
<script type="text/javascript" src="javascript/jquery-1.2.6.min.js"></script>
<script type="text/javascript" src="javascript/jquery.jparallax.js"></script>

<script type="text/javascript" src="javascript/form_js.js"></script>
<link href="styles.css" rel="stylesheet" type="text/css" media="all" />
<title>
<?php
if($title){echo $title; }else{ echo "Generic Title";}
?>
</title>
<script type="text/javascript">
jQuery(document).ready(function(){
	jQuery('#parallax').jparallax({});
});
</script>
<script type="text/javascript" src="javascript/iepngfix_tilebg.js"></script>
</head>
<body>
<div id="container">
<div id="header">	

<h1><a class="blogname" href="http://www.seaviewhotel.com.au">Seaview Hotel</a></h1>
<div id="parallax">    	
<div style="width: 1265px; height: 387px;">
		<img style="position:absolute; top:0px; left:15px;" alt="" src="images/stripes.png"/>
	</div>
	<div style="width: 1050px; height: 272px;">
		<img style="position:absolute; top:0px; left:0px;" alt="" src="images/back.png"/>
	</div>

	<div style="width: 1025px; height: 272px;">
		<img style="position:absolute; top:-3px; left:5px;" alt="" src="images/Wave.png"/>
	</div>

</div>
  </div>




